freebsd_instance:
  image_family: freebsd-12-2

test_task:
  name: "Tests / FreeBSD / "
  only_if: $CIRRUS_TAG == ''
  skip: "!changesInclude('.cirrus.yml', 'poetry.lock', 'pyproject.toml', '**.json','**.py')"
  env:
    matrix:
      - PYTHON: python3.6
      - PYTHON: python3.8
  python_script:
    - PYPACKAGE=$(printf '%s' $PYTHON | tr -d '.')
    - SQLPACKAGE=$(printf '%s-sqlite3' $PYPACKAGE | sed 's/thon//')
    - pkg install -y git-lite curl $PYPACKAGE $SQLPACKAGE
  pip_script:
    - $PYTHON -m ensurepip
    - $PYTHON -m pip --disable-pip-version-check install -U pip tox virtualenv
  poetry_script:
    - curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py \
      | $PYTHON - -y
    - poetry config virtualenvs.in-project true
  tox_script: $PYTHON -m tox -e py -- -q --junitxml=junit.xml tests
  on_failure:
    annotate_failure_artifacts:
      path: junit.xml
      format: junit
      type: text/xml
