- id: poetry-check
  name: poetry-check
  description: run poetry check to validate config
  entry: poetry check
  language: python
  pass_filenames: false
  files: ^(.*/)?pyproject\.toml$

- id: poetry-lock
  name: poetry-lock
  description: run poetry lock to update lock file
  entry: poetry lock
  language: python
  pass_filenames: false
  files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

- id: poetry-export
  name: poetry-export
  description: run poetry export to sync lock file with requirements.txt
  entry: poetry export
  language: python
  pass_filenames: false
  files: ^(.*/)?poetry\.lock$
  args: ["-f", "requirements.txt", "-o", "requirements.txt"]

- id: poetry-sync
  name: poetry-sync
  description: Synchronize the Poetry dependencies with the lock file if out of sync
  entry: poetry install
  language: python
  pass_filenames: false
  stages: [post-checkout, post-merge]
  always_run: true
  args: ["--sync"]
