
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='poetry',
    version='0.12.17',
    description='Python dependency management and packaging made easy.',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<4.0,>=2.7',
    project_urls={'homepage': 'https://poetry.eustace.io/', 'repository': 'https://github.com/sdispater/poetry', 'documentation': 'https://poetry.eustace.io/docs'},
    author='Sébastien Eustace',
    author_email='sebastien@eustace.io',
    license='MIT',
    keywords='packaging dependency poetry',
    classifiers=['Topic :: Software Development :: Build Tools', 'Topic :: Software Development :: Libraries :: Python Modules'],
    entry_points={'console_scripts': ['poetry = poetry.console:main']},
    packages=['poetry', 'poetry.console', 'poetry.console.commands', 'poetry.console.commands.cache', 'poetry.console.commands.debug', 'poetry.console.commands.self', 'poetry.console.styles', 'poetry.installation', 'poetry.io', 'poetry.json', 'poetry.layouts', 'poetry.masonry', 'poetry.masonry.builders', 'poetry.masonry.publishing', 'poetry.masonry.utils', 'poetry.mixology', 'poetry.packages', 'poetry.packages.constraints', 'poetry.packages.utils', 'poetry.puzzle', 'poetry.puzzle.operations', 'poetry.repositories', 'poetry.semver', 'poetry.spdx', 'poetry.utils', 'poetry.vcs', 'poetry.version'],
    package_data={'poetry.json': ['schemas/*.json'], 'poetry.spdx': ['data/*.json']},
    install_requires=['cachecontrol[filecache]==0.*,>=0.12.4', 'cachy==0.*,>=0.2.0', 'cleo==0.*,>=0.6.7', 'functools32==3.*,>=3.2.3; python_version == "2.7.*" and python_version >= "2.7.0"', 'glob2==0.*,>=0.6.0; python_version == "2.7.*" and python_version >= "2.7.0" or python_version == "3.4.*" and python_version >= "3.4.0"', 'html5lib==1.*,>=1.0.0', 'jsonschema==3.*,>=3.0.0', 'pathlib2==2.*,>=2.3.0; python_version == "2.7.*" and python_version >= "2.7.0" or python_version == "3.4.*" and python_version >= "3.4.0"', 'pkginfo==1.*,>=1.4.0', 'pyparsing==2.*,>=2.2.0', 'pyrsistent==0.*,>=0.14.2', 'requests==2.*,>=2.18.0', 'requests-toolbelt==0.*,>=0.8.0', 'shellingham==1.*,>=1.1.0', 'subprocess32==3.*,>=3.5.0; python_version == "2.7.*" and python_version >= "2.7.0" or python_version == "3.4.*" and python_version >= "3.4.0"', 'tomlkit==0.*,>=0.5.1', 'typing==3.*,>=3.6.0; python_version == "2.7.*" and python_version >= "2.7.0" or python_version == "3.4.*" and python_version >= "3.4.0"', 'virtualenv==16.*,>=16.0.0; python_version == "2.7.*" and python_version >= "2.7.0"'],
    extras_require={'dev': ['black==19.*,>=19.3.0; python_version == "3.*" and python_version >= "3.6.0"', 'httpretty==0.*,>=0.9.6', 'mkdocs==1.*,>=1.0.0; python_version == "2.7.*" and python_version >= "2.7.9" or python_version == "3.*" and python_version >= "3.4.0"', 'pre-commit==1.*,>=1.10.0', 'pygments==2.*,>=2.2.0', 'pygments-github-lexers==0.*,>=0.0.5', 'pymdown-extensions==6.*,>=6.0.0', 'pytest==4.*,>=4.1.0', 'pytest-cov==2.*,>=2.5.0', 'pytest-mock==1.*,>=1.9.0', 'pytest-sugar==0.*,>=0.9.2', 'tox==3.*,>=3.0.0']},
)
