name: "\U0001F4DA Documentation Issue"
labels: ["area/docs", "status/triage"]
description: "Did you find errors, omissions, or anything unintelligible in the documentation?"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete bug report.

        Before submitting your issue, please review the [Suggesting enhancements](https://python-poetry.org/docs/contributing/#suggesting-enhancements) section of our documentation.

        Please also confirm the following:
        - I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
        - I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

  - type: dropdown
    attributes:
      label: Issue Kind
      description: |
        What best describes the issue?
      options:
        - "Improving documentation"
        - "Missing documentation"
        - "Error in existing documentation"
        - "Unclear documentation"
        - "Other concerns with documentation"
    validations:
      required: true

  - type: input
    attributes:
      label: Existing Link
      description: |
        If the documentation in question exists, please provide a link to it.
      placeholder: "https://python-poetry.org/docs/dependency-specification/#version-constraints"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe the feature, with as much pertinent information as you can. Feel free to use markdown syntax.
      render: "Markdown"
    validations:
      required: true
