# this file is generated by tests/repositories/fixtures/pypi.org/generate.py
from __future__ import annotations

import dataclasses

from typing import TYPE_CHECKING

import pytest


if TYPE_CHECKING:
    from tests.types import DistributionHashGetter


@dataclasses.dataclass
class DistributionHash:
    sha256: str = ""
    md5: str = ""


KNOWN_DISTRIBUTION_HASHES = {
    "SQLAlchemy-1.2.12.tar.gz": DistributionHash(
        "b5a127599b3f27847fba6119de0fcb70832a8041b103701a708b7c7d044faa38",
        "4a2617b5254748828d09349fc4eff6bd",
    ),
    "Twisted-18.9.0.tar.bz2": DistributionHash(
        "4335327da58be11dd6e482ec6b85eb055bcc953a9570cd59e7840a2ce9419a8e",
        "35ff4705ea90a76bf972ff3b229546ca",
    ),
    "attrs-17.4.0-py2.py3-none-any.whl": DistributionHash(
        "d38e57f381e891928357c68e300d28d3d4dcddc50486d5f8dfaf743d40477619",
        "9d32f2b5a93343e01f54d87740f2da60",
    ),
    "attrs-17.4.0.tar.gz": DistributionHash(
        "eb7536a1e6928190b3008c5b350bdf9850d619fff212341cd096f87a27a5e564",
        "c03e5b3608d9071fbd098850d8922668",
    ),
    "black-19.10b0-py36-none-any.whl": DistributionHash(
        "3471ff321348d851b6f3047f4ed42c88622ac038caf7c2d160bd653334c88e88",
        "4a420234749e1ea350581160ef51cd02",
    ),
    "black-19.10b0.tar.gz": DistributionHash(
        "6cada614d5d2132698c6d5fff384657273d922c4fffa6a2f0de9e03e25b8913a",
        "c383543109a66a5a99113e6326db5251",
    ),
    "black-21.11b0-py3-none-any.whl": DistributionHash(
        "e16b6879ed61f9268994b879174fad1cb2319a651afd20f8cf036428ac65f846",
        "294e105f34e2e21286a49bfcfb8fb6ae",
    ),
    "black-21.11b0.tar.gz": DistributionHash(
        "f23c482185d842e2f19d506e55c004061167e3c677c063ecd721042c62086ada",
        "f01267bf2613f825dd6684629c1c829e",
    ),
    "cleo-1.0.0a5-py3-none-any.whl": DistributionHash(
        "20dbd69ed5c27e2889a2d428b9b01771f6073e4a1483a731e3c14c07a666aa9f",
        "eaf14b3f99b2b88c0846ecc9a5a18af4",
    ),
    "cleo-1.0.0a5.tar.gz": DistributionHash(
        "88f0a4275a17f2ab4d013786b8b9522d4c60bd37d8fc9b3def0fb27f4ac1e694",
        "92e181952976e09b9d1c583da6c3e2fc",
    ),
    "clikit-0.2.4-py2.py3-none-any.whl": DistributionHash(
        "60900adbac91d6d2cefc88efe2639ce3090f4520106596ac855bee3763f276c0",
        "c3558fef2a1148bb1df96376def5c8fe",
    ),
    "clikit-0.2.4.tar.gz": DistributionHash(
        "0fdd41e86e8b118a8b1e94ef2835925ada541d481c9b3b2fc635fa68713e6125",
        "f7cdbad3508038a04561f646aae68146",
    ),
    "colorama-0.3.9-py2.py3-none-any.whl": DistributionHash(
        "5b632359f1ed2b7676a869812ba0edaacb99be04679b29eb56c07a5e137ab5a2",
        "faef2bbd3c2ecc43e0969877d67b4c92",
    ),
    "colorama-0.3.9.tar.gz": DistributionHash(
        "4c5a15209723ce1330a5c193465fe221098f761e9640d823a2ce7c03f983137f",
        "8323a5b84fdf7ad810804e51fc256b39",
    ),
    "demo-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "70e704135718fffbcbf61ed1fc45933cfd86951a744b681000eaaa75da31f17a",
        "15507846fd4299596661d0197bfb4f90",
    ),
    "demo-0.1.0.tar.gz": DistributionHash(
        "9fa123ad707a5c6c944743bf3e11a0e80d86cb518d3cf25320866ca3ef43e2ad",
        "d1912c917363a64e127318655f7d1fe7",
    ),
    "demo-0.1.2-py2.py3-none-any.whl": DistributionHash(
        "55dde4e6828081de7a1e429f33180459c333d9da593db62a3d75a8f5e505dde1",
        "53b4e10d2bfa81a4206221c4b87843d9",
    ),
    "demo_invalid_record-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "d1e5a3f18f24a2ad3717c6f9c55f8c26060f39b2cddf28b18c355786728cb4dd",
        "18041168d415370d5019ec7e2b1ed0b5",
    ),
    "demo_invalid_record2-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "e730fca385b52e77fc58d73812f0dc236fad489ef6026716d1a4317ab4738c3c",
        "a21ee67e833f50e9f0ecdfe1c0484b93",
    ),
    "demo_metadata_version_23-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "7592aa158137726d9579e5d4347bd03a88f9fc82e11061303215feaaf000d32c",
        "434114a36f986671d132033e130f26b7",
    ),
    "demo_metadata_version_unknown-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "d716cd66546468ec3d4d40f4a4ecc813e3e4c661e155ecbc3a932f47d46d6e05",
        "749f823ff755a2f46bfb5ab25fdf9810",
    ),
    "demo_missing_dist_info-0.1.0-py2.py3-none-any.whl": DistributionHash(
        "cf8eaade81dd1db42f60c0e9c8610c1c12006baa9f7ad994b1c2bae92ea4b426",
        "da33c6088e72fbaaf873999606767353",
    ),
    "demo_no_pkg_info-0.1.0.tar.gz": DistributionHash(
        "f1e2a977c506dfb6b43495e2ffeee618b90029bac92fcb3038a53268197afa0c",
        "eeaf257d6b2c3b01def567751b21c1e8",
    ),
    "discord.py-2.0.0-py3-none-any.whl": DistributionHash(
        "054c3d8cf89a8e37a691e0268232dad23e07f4e9a06f33454c3bafeaba34a9b7",
        "8ffc907807f8351401dbe4408dcaff79",
    ),
    "discord.py-2.0.0.tar.gz": DistributionHash(
        "b86fa9dd562684f7a52564e6dfe0216f6c172a009c0d86b8dea8bdd6ffa6b1f4",
        "6c0505a6032342b29f31f9979f37d277",
    ),
    "futures-3.2.0-py2-none-any.whl": DistributionHash(
        "d89e1540e8b553fbda912230db359954365a1f5d0d0fa7fab96ad3969d9d5a93",
        "33e76564a87766c3e186d986ddc55bd8",
    ),
    "futures-3.2.0.tar.gz": DistributionHash(
        "baf0d469c9e541b747986b7404cd63a5496955bd0c43a3cc068c449b09b7d4a4",
        "40eb168dab84e606df3fdb7e67fe27b7",
    ),
    "hbmqtt-0.9.6.tar.gz": DistributionHash(
        "379f1d9044997c69308ac2e01621c817b5394e1fbe0696e62538ae2dd0aa7e07",
        "b284e3118882f169aa618a856cd91c5f",
    ),
    "ipython-5.7.0-py2-none-any.whl": DistributionHash(
        "3d93d3995e2e52a98dc4f44361cd5bf68dbde62925d1f820b97d8f0e1d941f73",
        "cf35939995e0fd8c44fca7509308abde",
    ),
    "ipython-5.7.0-py3-none-any.whl": DistributionHash(
        "b94c7a3971290024ffaa916d51ee377ee85f8860a62b5f30c58f5376f0956a06",
        "8805d83c415de06f5eadd55aeb2fa738",
    ),
    "ipython-5.7.0.tar.gz": DistributionHash(
        "4e7fb265e0264498bd0d62c6261936a658bf3d38beb8a7b10cd2c6327c62ac2a",
        "01f2808ebe78ff2f28dc39be3aa635ca",
    ),
    "ipython-7.5.0-py3-none-any.whl": DistributionHash(
        "634f505893bbbdb79d1a04d89f4633d8cfc41115337847fbf9d5a23610fc3e3d",
        "99a386eca39b536033c71aacf9f98e2b",
    ),
    "ipython-7.5.0.tar.gz": DistributionHash(
        "cd2a17ac273fea8bf8953118a2d83bad94f592f0db3e83fff9129a1842e36dbe",
        "0e8c1d7c14f309f6cd2dfd4e48e75cb1",
    ),
    "isort-4.3.4-py2-none-any.whl": DistributionHash(
        "3bbfc8f6119a46a48064487afb0b3ca9daa4b09fbfd94336a24c7616b71db2ca",
        "e84fb6f2278ee4d0bd719a4d44863d9f",
    ),
    "isort-4.3.4-py3-none-any.whl": DistributionHash(
        "e7aa083302c758b358e10a3a1c707adcc9f8ab57795e99246ac72eeffe7f2b20",
        "baa2e5dc4e89511b6bc54e969d040a08",
    ),
    "isort-4.3.4.tar.gz": DistributionHash(
        "234ad07e1e2780c27fa56364eefa734bee991b0d744337ef7e7ce3d5b1b59f39",
        "9244631852cf8bd8559f7ab78bf4ec78",
    ),
    "jupyter-1.0.0-py2.py3-none-any.whl": DistributionHash(
        "83c4591b9c7392ea5f91e0d9f8e98d894f76e8e669260788f0fcb281ec0b3b1f",
        "b2f5e2daab779c7bda0be38925ab1b92",
    ),
    "jupyter-1.0.0.tar.gz": DistributionHash(
        "3ef1e86ba0556ea5922b846416a41acfd2625830d996c7d06d80c90bed1dc193",
        "78acaec88533ea6b6e761e7d086a1d04",
    ),
    "jupyter-1.0.0.zip": DistributionHash(
        "4a855b9717c3ea24fd8ca4fd91ab5995894aecc4d20e7f39c28786a2c1869fae",
        "7b7a957694a73ac0c19fe46c216c0ea0",
    ),
    "more-itertools-4.1.0.tar.gz": DistributionHash(
        "bab2dc6f4be8f9a4a72177842c5283e2dff57c167439a03e3d8d901e854f0f2e",
        "bf351a1050242ce3af7e475a4da1a26b",
    ),
    "more_itertools-4.1.0-py2-none-any.whl": DistributionHash(
        "5dd7dfd88d2fdaea446da478ffef8d7151fdf26ee92ac7ed7b14e8d71efe4b62",
        "c70269eabc5fae5e0d93c2eca638720e",
    ),
    "more_itertools-4.1.0-py3-none-any.whl": DistributionHash(
        "29b1e1661aaa56875ce090fa219fa84dfc13daecb52cd4fae321f6f57b419ec4",
        "26d7c309ef806b4e563d2a7e4ceafb14",
    ),
    "pastel-0.1.0-py3-none-any.whl": DistributionHash(
        "d88b34efa115392ee42c55d6f82cdf5e5e08221ef2e18a16ae696a80008c3499",
        "632fcf45cc28aed4a4dce1324d1bd1d1",
    ),
    "pastel-0.1.0.tar.gz": DistributionHash(
        "22f14474c4120b37c54ac2173b49b0ac1de9283ca714be6eb3ea8b39296285a9",
        "43ea5f07660f630da18ae1827f5b4333",
    ),
    "pluggy-0.6.0-py2-none-any.whl": DistributionHash(
        "9b835f86bfe5498c87ace7f4899cb1b0c40e71c9277377f6851c74a307879285",
        "de6f342e8044d0071eefc3c9cda33055",
    ),
    "pluggy-0.6.0-py3-none-any.whl": DistributionHash(
        "8c646771f5eab7557d1f3924077c55408e86bdfb700f7d86a6d83abeabff4c66",
        "f2fc2c3179edccaa7728650178c9133c",
    ),
    "pluggy-0.6.0.tar.gz": DistributionHash(
        "a982e208d054867661d27c6d2a86b17ba05fbb6b1bdc01f42660732dd107f865",
        "ef8a88abcd501afd47cb22245fe4315a",
    ),
    "poetry_core-1.5.0-py3-none-any.whl": DistributionHash(
        "e216b70f013c47b82a72540d34347632c5bfe59fd54f5fe5d51f6a68b19aaf84",
        "be7589b4902793e66d7d979bd8581591",
    ),
    "poetry_core-1.5.0.tar.gz": DistributionHash(
        "0ae8d28caf5c12ec1714b16d2e7157ddd52397ea6bfdeba5a9432e449a0184da",
        "3f9b36a7a94cd235bfd5f05794828445",
    ),
    "py-1.5.3-py2.py3-none-any.whl": DistributionHash(
        "43ee6c7f95e0ec6a906de49906b79d138d89728fff17109d49f086abc2fdd985",
        "98652ecee6fc3bb5393a17828f93e1fb",
    ),
    "py-1.5.3.tar.gz": DistributionHash(
        "2df2c513c3af11de15f58189ba5539ddc4768c6f33816dc5c03950c8bd6180fa",
        "623e80cfc06df930414a9ce4bf0fd6c9",
    ),
    "pytest-3.5.0-py2.py3-none-any.whl": DistributionHash(
        "28e4d9c2ae3196d74805c2eba24f350ae4c791a5b9b397c79b41506a48dc64ca",
        "d3b1e9aea9e5b9e7a226d8b08aa43662",
    ),
    "pytest-3.5.0.tar.gz": DistributionHash(
        "677b1d6decd29c041fe64276f29f79fbe66e40c59e445eb251366b4a8ab8bf68",
        "ccd78dac54112045f561c4df86631f19",
    ),
    "pytest-3.5.1-py2.py3-none-any.whl": DistributionHash(
        "6d3e83b1c1697d220137e436980e73b3ca674f643e666d7c24b0321cb57b76a4",
        "f1de372a436700e3a785e85c11d15821",
    ),
    "pytest-3.5.1.tar.gz": DistributionHash(
        "b8fe151f3e181801dd38583a1c03818fbc662a8fce96c9063a0af624613e78f8",
        "961104636090457187851ccb9ef0f677",
    ),
    "python-language-server-0.21.2.tar.gz": DistributionHash(
        "91b564e092f3135b2bac70dbd23d283da5ad50269766a76648787b69fe702c7e",
        "677602ec38bc1c7b72de6128d90d846b",
    ),
    "requests-2.18.4-py2.py3-none-any.whl": DistributionHash(
        "ce91d39dc2857eeb19fc8bf765df6c14874bcdc724d3ce9c6cd89915618e7023",
        "f392c0ab49bf677c6240ef2b1890b079",
    ),
    "requests-2.18.4.tar.gz": DistributionHash(
        "ec62f7e0e9d4814656b0172dbd592fea06127c6556ff5651eb5d2c8768671fd4",
        "942a6a383dc94da90cf58f5adcf028a4",
    ),
    "setuptools-67.6.1-py3-none-any.whl": DistributionHash(
        "e728ca814a823bf7bf60162daf9db95b93d532948c4c0bea762ce62f60189078",
        "3b5b846e000da033d54eeaaf7915126e",
    ),
    "setuptools-67.6.1.tar.gz": DistributionHash(
        "a737d365c957dd3fced9ddd246118e95dce7a62c3dc49f37e7fdd9e93475d785",
        "ee2562f783544d1f95022c906dd3cf98",
    ),
    "six-1.11.0-py2.py3-none-any.whl": DistributionHash(
        "112f5b46e6aa106db3e4e2494a03694c938f41c4c4535edbdfc816c2e0cb50f2",
        "35b1057b388e276352d0709138b1e194",
    ),
    "six-1.11.0.tar.gz": DistributionHash(
        "268a4ccb159c1a2d2c79336b02e75058387b0cdbb4cea2f07846a758f48a356d",
        "25d3568604f921dd23532b88a0ce17e7",
    ),
    "tomlkit-0.5.2-py2.py3-none-any.whl": DistributionHash(
        "a50f685abd033a7b50b13330833c15699885186517b713d9f7e8280ce7976e4c",
        "7bcf6cf4a6034339bb6a481f27b9ba62",
    ),
    "tomlkit-0.5.2.tar.gz": DistributionHash(
        "4a226ccf11ee5a2e76bfc185747b54ee7718706aeb3aabb981327249dbe2b1d4",
        "7c31987ef6fba2cd64715cae27fade64",
    ),
    "tomlkit-0.5.3-py2.py3-none-any.whl": DistributionHash(
        "d4fe74be9b732d76886da6da2e96f76ae42551e53afce1ea29bc703629b70497",
        "b868779f054c64bc6c2ae4ad2cdbf6b3",
    ),
    "tomlkit-0.5.3.tar.gz": DistributionHash(
        "e2f785651609492c771d9887ccb2369d891d16595d2d97972e2cbe5e8fb3439f",
        "cdbdc302a184d1f1e38d5e0810e3b212",
    ),
    "wheel-0.40.0-py3-none-any.whl": DistributionHash(
        "d236b20e7cb522daf2390fa84c55eea81c5c30190f90f29ae2ca1ad8355bf247",
        "517d39f133bd7b1ff17caf09784b7543",
    ),
    "wheel-0.40.0.tar.gz": DistributionHash(
        "5cb7e75751aa82e1b7db3fd52f5a9d59e7b06905630bed135793295931528740",
        "5f175a8d693f74878964d4fd29729ab7",
    ),
    "zipp-3.5.0-py3-none-any.whl": DistributionHash(
        "82da6dcae3676123d6f493a876259614e7e6e970b14c59b1830a2c901ed91306",
        "52aecc0484efd07d62575d152f6a98f6",
    ),
    "zipp-3.5.0.tar.gz": DistributionHash(
        "239d50954a15aa4b283023f18dc451ba811fb4d263f4dd6855642e4d1c80cc9f",
        "16bf2a24fae340052e8565c264d21092",
    ),
}


@pytest.fixture
def dist_hash_getter() -> DistributionHashGetter:
    def get_hash(name: str) -> DistributionHash:
        return KNOWN_DISTRIBUTION_HASHES.get(name, DistributionHash())

    return get_hash
